### ISSUE TITLE
How to prevent a directory traversal attack?

### ISSUE THREAD

**Issue by pratheekrebala** [mrmlnc/fast-glob#130]
### Environment

  * OS Version: OS X
  * Node.js Version: 10

### Actual behavior
The tool currently allows for glob patterns to traverse directories outside the `baseDir`. This could allow for a [directory traversal attack](https://en.wikipedia.org/wiki/Directory_traversal_attack).

### Expected behavior
It would be awesome if there is a setting that would allow the user to disable traversal beyond the baseDirectory or if there would be a way to set the root directory for the glob patterns.

I understand if this is something that the user should be sanitizing before supplying the input to this package. However, it would be awesome to be able to enforce this at the module level.

### Steps to reproduce

  1. Pass in a path containing `../../*` or `/../../*` to the `fg.async` or any other `fg` method.

### Code sample

```js
const fg = require('fast-glob');
const dirs = fg.async(`../../*`, {
        deep: 1,
        transform: f => path.basename(f)
});
```

Thank you again for all your work on this amazing project!

**Comment by pratheekrebala** [comment]
One naive way to resolve this could be resolving the pattern and checking the prefix:

```
const path = require('path);
const globPattern = "test/../../*";
const baseDirectory = process.cwd(); // (Default)

function pathIsSafe(globPattern, baseDirectory) {
    const globPath = path.resolve(baseDirectory, globPattern);
    const pathIsSafe = globPath.substring(0, baseDirectory.length) === baseDirectory;

    if (!pathIsSafe) throw new Error('Directory Traversal not allowed');
    else return true
}
```

<sub><sup>h/t https://security.stackexchange.com/questions/123720/how-to-prevent-directory-traversal-when-joining-paths-in-node-js</sub></sup>

**Comment by mrmlnc** [comment]
Hi, @pratheekrebala,

I'm sorry for the late response.

Unfortunately, I don't think it should be part of this package.

Since it is not a CLI utility – the user (programmer) can correct/validate/modify the input data itself.  This package provides a low-level API for working with the file system and patterns (you can think of it as part of the standard library, like `glob` in the Python).

If I had to implement protection against this problem, I would also use the built-in methods to work with paths in the Node.js like `path.resolve`. Also you can check availability `..` in pattern.
