### ISSUE TITLE
Automocking of os causes fast-glob to break.

### ISSUE THREAD

**Issue by phawxby** [mrmlnc/fast-glob#363]
Using `jest.mock('os');` causes all functions to return undefined.

```
    TypeError: Cannot read properties of undefined (reading 'length')

      at Object.<anonymous> (node_modules/fast-glob/out/settings.js:6:28)
      at Object.<anonymous> (node_modules/fast-glob/out/index.js:6:20)
```

https://github.com/mrmlnc/fast-glob/blob/2ff5a2f370b9362c0fe239573530f1f804fe4a57/src/settings.ts#L10

Something like this could be a potentially simple fix to make it more resilient.
```
const CPU_COUNT = Math.max((os.cpus() || []).length, 1);
```

**Comment by mrmlnc** [comment]
Hello, @phawxby,

In my opinion this is correct behavior, because you are override one of the kernel modules of the platform. In the `os` module in Node.js, there can be no situation where this method returns the `undefined` as result.

https://github.com/nodejs/node/blob/917fcb20442c449f386efb10134c852f3aa5b7b1/lib/os.js#L135

I believe that this crutch solves only one problem among many that you may encounter in the future. Because you will need to make this change in every package that uses methods from the `os` module.

For example, this can happen with the following methods from this module:

* [`os.tmpdir`](https://nodejs.org/dist/latest-v18.x/docs/api/os.html#ostmpdir);
* [`os.homedir`](https://nodejs.org/dist/latest-v18.x/docs/api/os.html#oshomedir);
* [`os.constants`](https://nodejs.org/dist/latest-v18.x/docs/api/os.html#os-constants);

With that formulation, I don't want to make the changes that you suggest in this issue. Unfortunately, I can only suggest that you refuse to replace the kernel module, or provide some default values using the appropriate jest methods (`.mockImplementation` or something like this).

**Comment by phawxby** [comment]
@mrmlnc I understand the argument that makes sense. Then how about a compromise where the CPU count is retrieved as part of class initialization so that the value can be changed which will also facilitate better unit testing. You will be able to test the `[]` return which you can't currently.

**Comment by phawxby** [comment]
@mrmlnc apologies in my haste to respond over the weekend and from my phone I didn't realise you commented on the issue and not the PR. I've updated #364 based on your comment above.
