### ISSUE TITLE
Ignore patterns are applied to the absolute path instead of  relative to the working directory

### ISSUE THREAD

**Issue by func0der** [mrmlnc/fast-glob#441]
### Environment

  * OS Version: Linux
  * Node.js Version: 20.13.1

### Actual behavior

```
[]
```

### Expected behavior

```
['index.test.js']
```

### Steps to reproduce

  1. Create a path `~/something/`
  2. Put a file `index.test.js` in there
  3. Run the thing

### Code sample

index.ts: 
```js
const fg = require('fast-glob');

const include = [ '**/*.{test,spec}.{js,mjs,cjs,ts,mts,cts,jsx,tsx}' ]
const globOptions = {
  absolute: true,
  ignore: [
    '**/something/**',
  ],
}

const foo = async () => {
        return await fg(include, globOptions);
}

foo().then(console.log);

```

The problem seems to be that the parameter `absolute` which is documented as an output control parameter (https://www.npmjs.com/package/fast-glob#output-control) is getting in the way of filtering.

I have not found the correct place in the code yet, but I figure that paths are RESOLVED first and then FILTERED, instead of FILTERED relatively to `cwd` first and then RESOLVED to their absolute counterparts.
 
I hope what I am getting to is clear. Maybe this is intentional behaviour, but i found no documented evidence of that anywhere.

**Comment by func0der** [comment]
Failing test case:

In `absolute.e2e.ts` add:

```
		{
			pattern: 'file.md',
			options: {
				ignore: [path.posix.join('**', 'fixtures', '**')],
				cwd: 'fixtures',
				absolute: true,
			},
			expected: () => {
				return ['<root>/fixtures/file.md'];
			},
		}
```

It should fail.
I opened up a new PR for the failing test.

This never surfaced since the ABSOLUTE CWD was always added in all test cases in front of the `ignore` pattern.

**Comment by webpro** [comment]
Facing the same issue. Just by looking at the code I'd guess the culprit is at `utils.pattern.matchAny` where the pattern (in `patternsRe`) now matches the `fullpath`.

Either:

- `patternsRe` should only match against `entryPath`, even if `absolute: true`, but that would mean `isSkippedByAbsoluteNegativePatterns` could be removed altogether?
- `patternsRe` should be filtered so it contains only absolute patterns before entering `utils.pattern.matchAny`, we could add an `isAbsolutePattern()` helper for this I guess

https://github.com/mrmlnc/fast-glob/blob/1e520c174e225b3ecdeced7283a05fcb002d1033/src/providers/filters/entry.ts#L69-L77

@mrmlnc What do you think? I'd be happy to try and submit a PR for this.

**Comment by webpro** [comment]
PR: https://github.com/mrmlnc/fast-glob/pull/445

**Comment by func0der** [comment]
Whoop. Nice. Let'S get that released.

Thanks for the hard work <3
