### ISSUE TITLE
Find `folder` that is not inside `folder`

### ISSUE THREAD

**Issue by vjpr** [mrmlnc/fast-glob#75]
Say you want to find all `node_modules` folders, but not `node_modules` folders nested inside them.

E.g.

```
- app
  - packages
    - foo
    - bar
      - node_modules <- Return this and don't search anything inside it.
        - baz
          - node_modules <- Don't return this, and don't even search it.
```

Can this be done with fast-glob?

It is [impossible with `node-glob`](https://github.com/isaacs/node-glob/issues/335), but would be cool if it were possible in `fast-glob`.

**Comment by mrmlnc** [comment]
Hello, @vjpr,

The `fast-glob` package have a optimization for this case. For example, we have the following file system tree:

```
app
└── packages
    ├── bar
    │   ├── b.json
    │   └── node_modules
    │       └── baz
    │           ├── c.json
    │           └── node_modules
    │               ├── d.json
    │               └── something
    └── foo
        └── a.json
```

This is output for the `deep` filter:

```
packages (readed)
packages/bar (readed)
packages/foo (readed)
packages/bar/node_modules (readed)
packages/bar/node_modules/baz (readed)
packages/bar/node_modules/baz/node_modules (excluded from reading by negative patterns)
```

And this is result of work:

```js
[ 'packages/bar/node_modules',
  'packages/bar/node_modules/baz',
  'packages/bar/node_modules/baz/c.json' ]
```

**Comment by mrmlnc** [comment]
More information about it in the `README.md`:

https://github.com/mrmlnc/fast-glob/blob/master/README.md#how-to-exclude-directory-from-reading

**Comment by mrmlnc** [comment]
Closed as outdated issue without a response. Feel free to create a new issue or reopen it.

**Comment by NMinhNguyen** [comment]
> More information about it in the `README.md` file:
> 
> [`master`/README.md#how-to-exclude-directory-from-reading](https://github.com/mrmlnc/fast-glob/blob/master/README.md?rgh-link-date=2018-02-27T18%3A48%3A29Z#how-to-exclude-directory-from-reading)

@mrmlnc hey, sorry to be commenting on a closed, but I'm happy to open a new one if you prefer. What's the right pattern to be used for finding all top-level `node_modules` in a monorepo? I tried `['**/node_modules', '!**/node_modules']` and `['**/node_modules', '!**/node_modules/**']` which didn't work, but `['**/node_modules', '!**/node_modules/**/*']` seemed to do the job. I mean, it sort of makes sense why the first pattern wouldn't because it's literally saying negate `**/node_modules` which is what I'm using to match in the first place, but the `README.md` made me think that that's what the negation pattern should be. I'm happy to open a docs PR once I've received an official reply - it seems like a common enough use case to warrant being mentioned in the `README.md`.
